# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJSXcTVv9mtX6fXqRwjXh94v2BeQnPvU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data used for each type of plots
data_plot = pd.DataFrame(np.random.randn(10, 4),
                  index=pd.date_range('1/1/2000', periods=10),
                  columns=['Amazon', 'Apple', 'Meta', 'Alphabet'])
data_plot.plot.bar(stacked=True)

# For bar plot
data_bar = pd.DataFrame(np.random.randint(low=2, high=100, size=(10,4)),columns=['Amazon', 'Apple', 'Meta', 'Alphabet'])
data_bar.plot.bar(stacked=True)

# For histogram
data_plot = pd.DataFrame(np.random.randn(10, 4),
                  index=pd.date_range('1/1/2000', periods=10),
                  columns=['Amazon', 'Apple', 'Meta', 'Alphabet'])
data_plot.plot.bar(stacked=True)

data_hist = pd.DataFrame({'Maths':np.random.randint(low=30, high=100, size=100),
                         'Science':np.random.randint(low=10, high=80, size=100),
                         'Language':np.random.randint(low=40, high=70, size=100)},
                         columns=['Maths', 'Science', 'Language'])
data_hist.plot.hist(bins=50)

data_box = pd.DataFrame(np.random.rand(10, 5), columns=['ME', 'ECE', 'EE', 'IT', 'CS'])
data_box.plot.box(stacked=True)

data_area = pd.DataFrame(np.random.rand(10, 4), columns=['Chennai', 'Bangalore', 'Coimbatore', 'Pune'])
data_area.plot.area(stacked=True)

data_scatter = pd.DataFrame(np.random.rand(50, 4), columns=['a', 'b', 'c', 'd'])
#data_scatter.plot.scatterplot(s=True)
plt.scatter(data_scatter['a'],data_scatter['b'])

data_pie = pd.DataFrame(3 * np.random.rand(5), index=['Rent', 'Grocery', 'Outing', 'EMI', 'Misc'], columns=['Expenses'])
data_pie.plot.pie(subplots=True)
#data_pie.plot.pie(autopct='%1.1f',startangle=90,subplots=True)

x=[1,2,3]
y1=[1,2,3]
y2=[2,4,6]

plt.plot(x,y1)
plt.show()

plt.plot(x,y1,label='y1',linewidth=10,color='green',marker='+')
plt.plot(x,y2,label='y2',color='blue',marker='*')
plt.xlabel('x')
plt.xlabel('y')
plt.title('multi line chart')
plt.legend()
plt.show()

# Data for bar plot
x1 = [1, 3, 4, 5, 6, 7, 9]
y1 = [4, 7, 2, 4, 7, 8, 3]


x2 = [2, 4, 6, 8, 10]
y2 = [5, 6, 2, 6, 2]

plt.bar(x1, y1, label="Blue", color='b')
plt.bar(x2, y2, label="G", color='g')
plt.xlabel("bar number")
plt.ylabel("bar height")
plt.title("Bar Chart Example")
plt.legend()
plt.show()

n = 5 + np.random.randn(10000)

m = [m for m in range(len(n))]
plt.bar(m, n)
plt.title("Raw Data")
plt.show()

# Data for scatter plot
x1 = [2, 3, 4]
y1 = [5, 5, 5]


x2 = [1, 2, 3, 4, 5]
y2 = [2, 3, 2, 3, 4]
y3 = [6, 8, 7, 8, 7]

plt.scatter(x1, y1)
plt.scatter(x2, y2, marker='v', color='r')
plt.scatter(x2, y3, marker='*', color='m')
plt.title('Scatter Plot Example')
plt.show()

# Data for stacked plot
idxes = [ 1,  2,  3,  4,  5,  6,  7,  8,  9]
arr1  = [23, 40, 28, 43,  8, 44, 43, 18, 17]
arr2  = [17, 30, 22, 14, 17, 17, 29, 22, 30]
arr3  = [15, 31, 18, 22, 18, 19, 13, 32, 39]

# Plot the stacked plot
plt.stackplot(idxes, arr1, arr2, arr3, labels=['r', 'g', 'b'], colors=['r', 'g', 'b'])
plt.legend()
plt.show()

# Data for pie plot
labels = 'S1', 'S2', 'S3'
sections = [56, 66, 24]
colors = ['c', 'g', 'y']

plt.pie(sections, labels=labels, colors=colors, autopct='%.2f%%', explode = (0, 0.1, 0))

# Data for subplots
def random_plots():
  xs = []
  ys = []


  for i in range(20):
    x = i
    y = np.random.randint(10)


    xs.append(x)
    ys.append(y)


  return xs, ys
random_plots()

# Plot subplots
fig = plt.figure()

ax1 = plt.subplot2grid(shape=(5,2), loc=(0,0), rowspan=1, colspan=2)
ax2 = plt.subplot2grid(shape=(5,2), loc=(1,0), rowspan=2, colspan=2)
ax3 = plt.subplot2grid(shape=(5,2), loc=(4,0), rowspan=1, colspan=1)
ax4 = plt.subplot2grid(shape=(5,2), loc=(4,1), rowspan=1, colspan=1)

x, y = random_plots()
ax1.plot(x, y)

x, y = random_plots()
ax2.plot(x, y)

x, y = random_plots()
ax3.plot(x, y)

x, y = random_plots()
ax4.plot(x, y)